### ISSUE TITLE
twine-verify-upload registers as "verify_upload" instead of "verify-upload"

### ISSUE THREAD

**Issue by pepoluan** [MrMino/twine-verify-upload#1]
**OS:** Windows 10.0.19042.0
**Python:** CPython 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
**twine:** twine version 3.3.0 (pkginfo: 1.7.0, requests: 2.25.1, setuptools: 53.0.0, requests-toolbelt: 0.9.1, tqdm: 4.56.0)

Reproducible error:

```sh
> twine verify-upload --config-file ..\pypirc.cfg dist/*
usage: twine [-h] [--version] [--no-color] {check,register,upload,verify_upload}
twine: error: argument command: invalid choice: 'verify-upload' (choose from 'check', 'register', 'upload', 'verify_upload')
```

What works (pleas ignore the mismatch; it's expected):

```sh
> twine verify_upload --config-file ..\pypirc.cfg dist/*
Using API endpoint at https://pypi.org/simple.

Looking for dist\aiosmtpd-1.3.0-py3-none-any.whl.
        Local:  64e6dd0c4c50cab3ac2964c7bba4b964
        Remote: <NOT FOUND>
Looking for dist\aiosmtpd-1.3.0.tar.gz.
        Local:  0de8cfb1fe094d37e5c6c66bc1f9ed6d8f11d8ae4ef914b03a5a4f91a64e957a
        Remote: 720c9f2a0baddc64b24437de12d1ba5819ba6dfc01f0b35e11dcd49b9185dbbe
```

So the documentation which stated:

> ```
> > twine verify-upload dists/* --fail-when=different
> Looking for dist/my-package-4.8.3.dev0-py2.py3-none-any.whl.
>         Local:  5b5e5bf19f75487d60ea872d678b408c                   
>         Remote: <NOT FOUND>
> ```

needs to be fixed.

**Comment by MrMino** [comment]
Ugh... That's unfortunate, I must've borked it at some point, and didn't realize because I was testing it via a bash script all the time. It _should_ be `verify-upload`, not `verify_upload`, but for the sake of compatibility I'm not changing it :).

Thanks for notifying me to this, I fixed the usage example in the README.
